name: Sync greasemonkey to (adamlui/userscripts/chatgpt || adamlui/chatgpt-userscripts) /autoclear-chatgpt-history

on:
  push:
    branches: [ master, main ]
    paths:
      - 'greasemonkey/**'

jobs:
  build:
    if: github.event.commits[0].committer.username != 'auto-sync-bot'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/autoclear-chatgpt-history
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/autoclear-chatgpt-history
          path: adamlui/autoclear-chatgpt-history

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout adamlui/chatgpt-userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-userscripts
          path: adamlui/chatgpt-userscripts

      - name: Copy greasemonkey/README.md to root directory
        run: cp -f ${{ github.workspace }}/adamlui/autoclear-chatgpt-history/greasemonkey/README.md ${{ github.workspace }}/adamlui/autoclear-chatgpt-history/README.md

      - name: Sync adamlui/autoclear-chatgpt-history/greasemonkey to adamlui/userscripts/chatgpt/autoclear-chatgpt-history
        run: rsync -av --delete ${{ github.workspace }}/adamlui/autoclear-chatgpt-history/greasemonkey/ ${{ github.workspace }}/adamlui/userscripts/chatgpt/autoclear-chatgpt-history/

      - name: Sync adamlui/autoclear-chatgpt-history/greasemonkey to adamlui/chatgpt-userscripts/autoclear-chatgpt-history
        run: rsync -av --delete ${{ github.workspace }}/adamlui/autoclear-chatgpt-history/greasemonkey/ ${{ github.workspace }}/adamlui/chatgpt-userscripts/autoclear-chatgpt-history/

      - name: Push to adamlui/autoclear-chatgpt-history
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@adamlui.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/autoclear-chatgpt-history/greasemonkey`]'
          file_pattern: '*'
          repository: adamlui/autoclear-chatgpt-history

      - name: Push to adamlui/userscripts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@adamlui.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/autoclear-chatgpt-history`]'
          file_pattern: 'chatgpt/autoclear-chatgpt-history/*'
          repository: adamlui/userscripts

      - name: Push to adamlui/chatgpt-userscripts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@adamlui.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/autoclear-chatgpt-history`]'
          file_pattern: 'autoclear-chatgpt-history/*'
          repository: adamlui/chatgpt-userscripts