name: Sync greasemonkey to adamlui/userscripts/chatgpt/autoclear-chatgpt-history

on:
  push:
    branches:
      - main
    paths:
      - 'greasemonkey/**'
    if: 'github.event.head_commit.committer.username != "auto-sync[bot]"'

jobs:
  sync-bravegpt:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/autoclear-chatgpt-history
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/autoclear-chatgpt-history
          path: adamlui/autoclear-chatgpt-history

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Sync adamlui/autoclear-chatgpt-history/greasemonkey to adamlui/userscripts/chatgpt/autoclear-chatgpt-history
        run: rsync -av --delete ${{ github.workspace }}/adamlui/autoclear-chatgpt-history/greasemonkey/ ${{ github.workspace }}/adamlui/userscripts/chatgpt/autoclear-chatgpt-history/

      - name: Push to adamlui/userscripts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_name: 'auto-sync[bot]'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/autoclear-chatgpt-history`]'
          file_pattern: 'chatgpt/autoclear-chatgpt-history/*'
          repository: adamlui/userscripts